[build]
publish = "public"
command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.79.0"
  GO_VERSION = "1.14"

[context.production]
[context.production.environment]
  HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_PRIME_URL"